"use client";

import { useEffect, useState } from "react";

import { DataTable, TableBadge, TablePrimaryCell } from "@/components/ui/DataTable";
import { Card, PageHeader } from "@/components/ui/primitives";
import { api } from "@/lib/api";

type SettlementRow = {
  id: string;
  settlementNumber: string;
  status: "PENDING" | "PAID" | "VOID";
  currency: string;
  grossAmount: string | number;
  commissionAmount: string | number;
  netAmount: string | number;
  periodStart: string;
  periodEnd: string;
};

function money(v: string | number | null | undefined) {
  if (v == null) return "—";
  return Number(v).toLocaleString();
}

export default function OperatorSettlementsPage() {
  const [rows, setRows] = useState<SettlementRow[]>([]);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    api<SettlementRow[]>("/tenant/settlements")
      .then(setRows)
      .catch((e) => setError(e instanceof Error ? e.message : "Failed to load"));
  }, []);

  return (
    <div>
      <PageHeader
        title="Settlements"
        subtitle="What TumaNow owes you after commission, generated by the platform each period."
      />

      {error ? <Card className="mb-4 text-sm text-[var(--tn-danger)]">{error}</Card> : null}

      <DataTable
        columns={[
          { key: "number", title: "Settlement" },
          { key: "period", title: "Period" },
          { key: "gross", title: "Gross" },
          { key: "commission", title: "Commission" },
          { key: "net", title: "Net payout" },
          { key: "status", title: "Status" },
        ]}
        emptyLabel="No settlements yet — the platform generates these periodically."
        rowKeys={rows.map((r) => r.id)}
        rows={rows.map((row) => ({
          number: <TablePrimaryCell primary={row.settlementNumber} />,
          period: `${new Date(row.periodStart).toLocaleDateString()} – ${new Date(row.periodEnd).toLocaleDateString()}`,
          gross: `${money(row.grossAmount)} ${row.currency}`,
          commission: `${money(row.commissionAmount)} ${row.currency}`,
          net: `${money(row.netAmount)} ${row.currency}`,
          status: (
            <TableBadge tone={row.status === "PAID" ? "success" : row.status === "VOID" ? "neutral" : "warning"}>
              {row.status}
            </TableBadge>
          ),
        }))}
      />
    </div>
  );
}
